### ISSUE TITLE
Feature request: split output

### ISSUE THREAD

**Issue by zeule** [tmedwards/tweego#14]
Could you, please, add options to skip assembling the final HTML file and instead output head, and the tw-storydata chunk as a whole or even split into components (metadata, script, tw-passagedata)? Independent compile and link steps, so to say.

If combined with an input file mask this can greatly help to setup build pipeline with sourcemaps, typescript, etc.?

**Comment by tmedwards** [comment]
Tweego can already be part of a build pipeline.  By which I mean, you can already transpile your code and CSS into bundles that are then compiled into your project by Tweego.  I do this myself in several projects.

How do you feel that your proposal significantly better than what's already currently possible?

**Comment by zeule** [comment]
That requires to keep twee and resources in a common directory, while putting scripts into a separate dir, or am I missing something? If not, that creates quite complicated directory structure. Having a partial compilation or an include/exclude masks would help to manage files in a much more flexible way.

**Comment by tmedwards** [comment]
You consider a single extra directory to be a *quite complicated* directory structure?

I'm sorry, I just don't see that.  Considering that you'd have to do something similar for the module option anyway, doing so for an internal bundle is, frankly, neither complicated, nor a chore.  I'm just not seeing the benefit here.
