### ISSUE TITLE
motoslave.net

### ISSUE THREAD

**Issue by Uzume** [tmedwards/tweego#16]
This might be the wrong place to bring this up but I thought it was incongruent that:

https://www.motoslave.net/

has a link to:

https://www.motoslave.net/sugarcube/

but not a link to:

https://www.motoslave.net/tweego/

If you are making changes to motoslave.net, it should be noted when I access it with secure https schema, my browser warns me it is using weak encryption due to it using TLS 1.0. In October 2018, TLS 1.0 and 1.1 were announced to be deprecated in March 2020 which has now past.

**Comment by tmedwards** [comment]
Done.

**Comment by Uzume** [comment]
@tmedwards It looks good--thanks for the added link and the change to TLS 1.3.

**Comment by Uzume** [comment]
@tmedwards FYI your website's TLS site certificate is now expired as FireFox is now providing me:
```
Websites prove their identity via certificates, which are valid for a set time period. The certificate for www.motoslave.net expired on 10/30/2021.
 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE
```

2021-11-19 Edit: I see this has since been fixed as current site certificate is now valid from 2021-11-02 to 2022-12-04 but apparently it was an issue from 2021-10-30 to 2021-11-02.
