### ISSUE TITLE
New Hrlowe 3.2.0

### ISSUE THREAD

**Issue by Beurt** [tmedwards/tweego#20]
Twine offers now a new Harlowe: 3.2.0. Currently, Tweego supports only the 3.1.0. Is there any plans to support Harlowe 3.2.0?

**Comment by tmedwards** [comment]
Unless something has changed to make it unable to be loaded, Tweego already supports Harlowe v3.2.0.  Thus, you can download it and add it to your story formats now.  If you need help with that, I'd suggest asking in the Twine Games Discord server's `compilers` channel (I suppose the `harlowe` channel might work too).

What I believe you mean to ask is will it be included in Tweego's distributions.  The answer to that is whenever a new Tweego release is made the most recent version of the included story formats are generally included.

**Comment by Beurt** [comment]
Thank you!
I'll try to find out how to include the v3.2.0 in my distribution (I am not fond of Discord...)

**Comment by Beurt** [comment]
In fact it is pretty straight forward. The new Harlow format is described here: <https://github.com/klembot/twinejs/tree/2.3-maintenance/story-formats/harlowe-3.2.0>. So one just have to [download the directory](https://downgit.github.io/#/home?url=https://github.com/klembot/twinejs/tree/2.3-maintenance/story-formats/harlowe-3.2.0), and unzip it into the `storyformat` directory of the tweego distribution.

Then it works, and you can decompile without setting the `-f` parameter (Harlowe 3.2.0 is automagically recognized).
