### ISSUE TITLE
No support for Harlowe 3.2.x–3.3.x

### ISSUE THREAD

**Issue by meffordm** [tmedwards/tweego#32]
Please add support for Harlowe 3.2.2, as it is now the default story format for Twine 2.

**Comment by tmedwards** [comment]
Harlowe v3.2.2 *should* work fine after you've installed it.  What problem, specifically, have you had with it?

**Comment by tmedwards** [comment]
Also.  See issue #20 for a previous issue on this topic.

**Comment by meffordm** [comment]
It was telling me that v3.2.2 wasn't recognized.

**Comment by glvno** [comment]
For anyone else having trouble, [Here](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/klembot/twinejs/tree/872f90342f6bfa03b741628aeaa570e621763fa3/story-formats/harlowe-3.2.2) is a direct link to the icon.svg and format.js for 3.2.2.

**Comment by coreydwillis** [comment]
@glvno I tried extracting the icon and format file from the latest v3.3.2 download, but that exports a blank file with no errors. When I revert to the v3.2.2 file you offered, it works again. How can I get any of the v3.3x versions to work?

**Comment by tmedwards** [comment]
**EDIT:** Doesn't look like v3.3.2 has actually been released yet.

**Comment by coreydwillis** [comment]
Thanks for the links! This is what I was using previously and I tried using your download links, but I'm still getting a blank page when it compiles, whereas if I go back to the v3.2.2, it works fine. It there something wrong with my configuration here?

![harlow3-storydata](https://user-images.githubusercontent.com/3526728/179523149-ebb4ccb7-7f40-49e6-9ae7-cfc6c5dd6405.png)
![harlow3](https://user-images.githubusercontent.com/3526728/179523151-1a9e6ccf-f7f7-4a3f-8386-e1f23272051f.png)

**Comment by tmedwards** [comment]
Actually, looking more closely.  I don't think v3.3.2 is even released yet.  It looks like v3.3.1 is the latest release in the v3.3.x series.

* [DownGit link to v3.3.1](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/klembot/twinejs/tree/develop/public/story-formats/harlowe-3.3.1)

**Comment by coreydwillis** [comment]
That worked, thanks! I tried downloading the whole v3.3.1 version before and just using those two specific files, but it didn't work. What did you do differently to get those two files?

**Comment by tmedwards** [comment]
In this instance I used the DownGit service—it's where the link goes.

You paste the URL within a Git repo to a file or directory—the Harlowe v3.3.1 directory from Twine v2.4's repo in this case—and it allows you to download the files.
