### ISSUE TITLE
Tweego crashing on launch

### ISSUE THREAD

**Issue by Dunxter** [tmedwards/tweego#48]
**Describe the bug**
Very shortly (not even 10 frames) after running tweego.exe, the program closes itself.

**Desktop (please complete the following information):**
 - Tweego Version 2.1.1
 - Win 10 22H2 compilation 19045.2130

**Additional context**
I've tried rebooting the system, running as admin and other compability settings (win 8, 7, etc.), but no results.  I've also tried the x86 version and no luck.

**Comment by tmedwards** [comment]
First.  You do realize that Tweego is a [command-line application](https://en.m.wikipedia.org/wiki/Command-line_interface), yes?  It doesn't create a window, you run it from a shell—e.g., included with Windows: cmd.exe, PowerShell.

I don't know what *frames* is supposed to represent in the context of executing a command-line application, but I'll assume it means quickly.

**Comment by Dunxter** [comment]
Ah I see. I'm really new to all this stuff so thank you for clearing this out!
