### ISSUE TITLE
Use image/svg+xml for SVGs instead of Base64

### ISSUE THREAD

**Issue by BawdyInkSlinger** [tmedwards/tweego#49]
**Is your feature request related to a problem?  Please describe.**
Tweego -- at least I think Tweego is doing this, let me know if I'm mistaken -- Base64's SVG files. I think it would be advantageous to use image/svg+xml instead. One of the reasons is it'll reduce the size of the output HTML and make the SVG code more human readable. 

See more information on the topic here: https://css-tricks.com/probably-dont-base64-svg/

**Describe alternatives you've considered.**
Nothing prevents me from doing this on my own, so that's always an alternative.

**Additional context**
The article says:

> For SVG, you don’t have to convert the data into base64. Again, not an expert here, but I think the SVG syntax just doesn’t have any crazy characters in it. It’s just XML like HTML is, so it’s safe to use in HTML.

I believe this is incorrect. I think there are certain characters you can put between `<script>` tags that can confuse the browser, and the solution to that problem is to wrap the body of `<script>` tags in a CDATA. 

And/or maybe the `#` symbols in the SVG colors make the browser think you are referencing a URL fragment, so you have to url encode those.

**Comment by tmedwards** [comment]
In the Twine ecosystem, media passages are expected to be Base-64 encoded by both tooling and story formats.  This cannot change.

If you don't want SVGs made into media passages, then don't provide the `.svg` files to Tweego as sources.  You have two fairly easy options here:

### 1. Embed them as regular passages

A regular passage that just happens to contain SVG markup.  SVGs don't have to be used as the source of an HTML `<img>` tag.  For example:

```
:: some.svg
/* SVG markup here */
```

Either put that passage into its own Twee file or into a group SVG Twee file.

Then simply include the passage where needed.  For example:

```
<<include "some.svg">>
```

For SugarCube users, an additional benefit to directly using SVG markup is that it's processed by SugarCube's SVG parser.  That allows various other features to be used within the SVG—e.g., attribute directives, data attributes, etc.

### 2. Don't embed them at all

You *can* use SVGs as loose resources.  For example:

```html
<img src="media/some.svg">
```
