### ISSUE TITLE
JS scripts outside the SugarCube envelope

### ISSUE THREAD

**Issue by ezsh** [tmedwards/tweego#6]
When there is a lot of JavaScript code in the game, it is tedious to declare global functions via assignments to the `window` object. It would be nice if there will be a way to tag .js files with global declarations so that Tweego could put them in a normal `<script>` tag instead of the SugarCube (or another format) scope. For example, a special comment at the beginning of the .js file could do the trick.

**Comment by tmedwards** [comment]
That's the purpose of the module option (`-m SRC`, `--module=SRC`).

**SEE:** [*Options*](http://www.motoslave.net/tweego/docs/#usage-options) in the manual.

**Comment by ezsh** [comment]
Thanks, but the option is a bit different: it requires to keep those modules in its own directory, while I ask for a tags in the source files. Although I'll completely understand if you reject this change.
