### ISSUE TITLE
Story.name Sugarcube 2.37.0 support

### ISSUE THREAD

**Issue by rohal12** [tmedwards/tweego#61]
https://github.com/tmedwards/tweego/blob/243cf70ed79e0c76caf7eeec34dc47a3aa12a922/tweego.go#L87-L89 checks for `s.name` but doesn't seem to load it anywhere.
SugarCube 2.37.0 has a new Story.name property that can be used in place of StoryTitle.

**Comment by tmedwards** [comment]
It's loaded on the line: https://github.com/tmedwards/tweego/blob/243cf70ed79e0c76caf7eeec34dc47a3aa12a922/story.go#L187-L189

What SugarCube has to do with anything I don't know.  It's properties are not available to Tweego and that property existed before now under another name.
