### ISSUE TITLE
Sugarcube typed.js addon doesn't work with tweego unless you make a script tagged passage

### ISSUE THREAD

**Issue by freezerburn26** [tmedwards/tweego#9]
The typed addon only works with tweego if you make a .twee and give it the [script] tag.

Including the .js file does nothing.

**Comment by tmedwards** [comment]
JavaScript files, either manually specified or found within a specified directory, that are part of a project's **normal sources** are compiled into the data chunk in exactly the same way as `script`-tagged passages.  Ensure you aren't confusing normal sources with module sources.

Assuming you're referring to the Typed.js integration module from SugarCube's website, how exactly are you compiling it into your project?  The `.js`, and `.css`, files from the package are meant to be used within SugarCube's scope, meaning that they need to be compiled as part of your normal sources—i.e., do not use Tweego's module option (`-m SRC`, `--module=SRC`) to include them as that bundles them external to SugarCube.

**Comment by freezerburn26** [comment]
Hello,

This does work. It might be a good idea to mention this in the docs somewhere.
